// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function CreateFetcherFactory(FC) {
  var CreateFetcher = function (C) {
    var url = FC[/* baseUrl */0] + C[/* url */1];
    var fetch$1 = function (payload, headers, _) {
      var body = payload ? /* Some */[Json.stringify(Curry._1(C[/* encodePayload */5], payload[0]))] : /* None */0;
      var headers$1 = Object.assign({
            "Content-Type": "application/json"
          }, Object.assign(Js_dict.fromList(C[/* headers */2]), Js_dict.fromList(headers ? headers[0] : /* [] */0)));
      return fetch(url, Fetch.RequestInit[/* make */0](/* Some */[C[/* method__ */4]], /* Some */[headers$1], body, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0));
    };
    var component = ReasonReact.reducerComponent(C[/* name */0]);
    var make = function (render, payload, headers, $staropt$star, _) {
      var lazy_ = $staropt$star ? $staropt$star[0] : false;
      return /* record */[
              /* debugName */component[/* debugName */0],
              /* reactClassInternal */component[/* reactClassInternal */1],
              /* handedOffState */component[/* handedOffState */2],
              /* willReceiveProps */(function (self) {
                  Curry._1(self[/* send */4], /* Fetch */0);
                  return self[/* state */2];
                }),
              /* didMount */(function (self) {
                  if (lazy_ === false) {
                    Curry._1(self[/* send */4], /* Fetch */0);
                  }
                  return /* NoUpdate */0;
                }),
              /* didUpdate */component[/* didUpdate */5],
              /* willUnmount */component[/* willUnmount */6],
              /* willUpdate */component[/* willUpdate */7],
              /* shouldUpdate */component[/* shouldUpdate */8],
              /* render */(function (self) {
                  return Curry._1(render, self[/* state */2]);
                }),
              /* initialState */(function () {
                  return /* record */[
                          /* data */C[/* defaultValue */3],
                          /* reason : None */0,
                          /* status : Idle */0
                        ];
                }),
              /* retainedProps */component[/* retainedProps */11],
              /* reducer */(function (action, state) {
                  if (typeof action === "number") {
                    if (action !== 0) {
                      return /* Update */Block.__(0, [/* record */[
                                  /* data */state[/* data */0],
                                  /* reason */state[/* reason */1],
                                  /* status : Idle */0
                                ]]);
                    } else {
                      return /* UpdateWithSideEffects */Block.__(3, [
                                /* record */[
                                  /* data */state[/* data */0],
                                  /* reason */state[/* reason */1],
                                  /* status : Fetching */1
                                ],
                                (function (self) {
                                    fetch$1(payload, headers, /* () */0).then((function (prim) {
                                                return prim.json();
                                              })).then((function (json) {
                                              Curry._1(self[/* send */4], /* ParseData */[/* Success */Block.__(0, [Curry._1(C[/* decodeState */6], json)])]);
                                              return Promise.resolve(null);
                                            })).catch((function (err) {
                                            console.log("Error: ", err);
                                            Curry._1(self[/* send */4], /* ParseData */[/* Failed */Block.__(1, ["Fetch Error"])]);
                                            return Promise.resolve(null);
                                          }));
                                    return /* () */0;
                                  })
                              ]);
                    }
                  } else {
                    var fetchedData = action[0];
                    if (typeof fetchedData === "number") {
                      return /* NoUpdate */0;
                    } else if (fetchedData.tag) {
                      return /* Update */Block.__(0, [/* record */[
                                  /* data */state[/* data */0],
                                  /* reason : Some */[fetchedData[0]],
                                  /* status : Failed */2
                                ]]);
                    } else {
                      return /* Update */Block.__(0, [/* record */[
                                  /* data */fetchedData[0],
                                  /* reason : None */0,
                                  /* status : Idle */0
                                ]]);
                    }
                  }
                }),
              /* subscriptions */component[/* subscriptions */13],
              /* jsElementWrapped */component[/* jsElementWrapped */14]
            ];
    };
    return /* module */[
            /* url */url,
            /* fetch */fetch$1,
            /* component */component,
            /* make */make
          ];
  };
  return /* module */[/* CreateFetcher */CreateFetcher];
}

var baseUrl = "/api/";

function CreateFetcher(C) {
  var url = baseUrl + C[/* url */1];
  var fetch$1 = function (payload, headers, _) {
    var body = payload ? /* Some */[Json.stringify(Curry._1(C[/* encodePayload */5], payload[0]))] : /* None */0;
    var headers$1 = Object.assign({
          "Content-Type": "application/json"
        }, Object.assign(Js_dict.fromList(C[/* headers */2]), Js_dict.fromList(headers ? headers[0] : /* [] */0)));
    return fetch(url, Fetch.RequestInit[/* make */0](/* Some */[C[/* method__ */4]], /* Some */[headers$1], body, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0));
  };
  var component = ReasonReact.reducerComponent(C[/* name */0]);
  var make = function (render, payload, headers, $staropt$star, _) {
    var lazy_ = $staropt$star ? $staropt$star[0] : false;
    return /* record */[
            /* debugName */component[/* debugName */0],
            /* reactClassInternal */component[/* reactClassInternal */1],
            /* handedOffState */component[/* handedOffState */2],
            /* willReceiveProps */(function (self) {
                Curry._1(self[/* send */4], /* Fetch */0);
                return self[/* state */2];
              }),
            /* didMount */(function (self) {
                if (lazy_ === false) {
                  Curry._1(self[/* send */4], /* Fetch */0);
                }
                return /* NoUpdate */0;
              }),
            /* didUpdate */component[/* didUpdate */5],
            /* willUnmount */component[/* willUnmount */6],
            /* willUpdate */component[/* willUpdate */7],
            /* shouldUpdate */component[/* shouldUpdate */8],
            /* render */(function (self) {
                return Curry._1(render, self[/* state */2]);
              }),
            /* initialState */(function () {
                return /* record */[
                        /* data */C[/* defaultValue */3],
                        /* reason : None */0,
                        /* status : Idle */0
                      ];
              }),
            /* retainedProps */component[/* retainedProps */11],
            /* reducer */(function (action, state) {
                if (typeof action === "number") {
                  if (action !== 0) {
                    return /* Update */Block.__(0, [/* record */[
                                /* data */state[/* data */0],
                                /* reason */state[/* reason */1],
                                /* status : Idle */0
                              ]]);
                  } else {
                    return /* UpdateWithSideEffects */Block.__(3, [
                              /* record */[
                                /* data */state[/* data */0],
                                /* reason */state[/* reason */1],
                                /* status : Fetching */1
                              ],
                              (function (self) {
                                  fetch$1(payload, headers, /* () */0).then((function (prim) {
                                              return prim.json();
                                            })).then((function (json) {
                                            Curry._1(self[/* send */4], /* ParseData */[/* Success */Block.__(0, [Curry._1(C[/* decodeState */6], json)])]);
                                            return Promise.resolve(null);
                                          })).catch((function (err) {
                                          console.log("Error: ", err);
                                          Curry._1(self[/* send */4], /* ParseData */[/* Failed */Block.__(1, ["Fetch Error"])]);
                                          return Promise.resolve(null);
                                        }));
                                  return /* () */0;
                                })
                            ]);
                  }
                } else {
                  var fetchedData = action[0];
                  if (typeof fetchedData === "number") {
                    return /* NoUpdate */0;
                  } else if (fetchedData.tag) {
                    return /* Update */Block.__(0, [/* record */[
                                /* data */state[/* data */0],
                                /* reason : Some */[fetchedData[0]],
                                /* status : Failed */2
                              ]]);
                  } else {
                    return /* Update */Block.__(0, [/* record */[
                                /* data */fetchedData[0],
                                /* reason : None */0,
                                /* status : Idle */0
                              ]]);
                  }
                }
              }),
            /* subscriptions */component[/* subscriptions */13],
            /* jsElementWrapped */component[/* jsElementWrapped */14]
          ];
  };
  return /* module */[
          /* url */url,
          /* fetch */fetch$1,
          /* component */component,
          /* make */make
        ];
}

var name = "RLimitFetcher";

var url = "rlimit";

var headers = /* :: */[
  /* tuple */[
    "ExtraHeader",
    "Pistachio-"
  ],
  /* [] */0
];

var defaultValue = /* record */[
  /* curCpuLimit */0,
  /* maxCpuLimit */0,
  /* curAsLimit */0,
  /* maxAsLimit */0,
  /* curStackLimit */0,
  /* maxStackLimit */0,
  /* curDataLimit */0,
  /* maxDataLimit */0
];

function encodePayload() {
  return null;
}

function decodeState(json) {
  return /* record */[
          /* curCpuLimit */Json_decode.field("cur_cpu_limit", Json_decode.$$int, json),
          /* maxCpuLimit */Json_decode.field("max_cpu_limit", Json_decode.$$int, json),
          /* curAsLimit */Json_decode.field("cur_as_limit", Json_decode.$$int, json),
          /* maxAsLimit */Json_decode.field("max_as_limit", Json_decode.$$int, json),
          /* curStackLimit */Json_decode.field("cur_stack_limit", Json_decode.$$int, json),
          /* maxStackLimit */Json_decode.field("max_stack_limit", Json_decode.$$int, json),
          /* curDataLimit */Json_decode.field("cur_data_limit", Json_decode.$$int, json),
          /* maxDataLimit */Json_decode.field("max_data_limit", Json_decode.$$int, json)
        ];
}

var RLimitConfig = /* module */[
  /* name */name,
  /* url */url,
  /* headers */headers,
  /* defaultValue */defaultValue,
  /* method__ : Get */0,
  /* encodePayload */encodePayload,
  /* decodeState */decodeState
];

var url$1 = "/api/rlimit";

function fetch$1(payload, headers$1, _) {
  var body = payload ? /* Some */[Json.stringify(null)] : /* None */0;
  var headers$2 = Object.assign({
        "Content-Type": "application/json"
      }, Object.assign(Js_dict.fromList(headers), Js_dict.fromList(headers$1 ? headers$1[0] : /* [] */0)));
  return fetch(url$1, Fetch.RequestInit[/* make */0](/* Some */[/* Get */0], /* Some */[headers$2], body, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0));
}

var component = ReasonReact.reducerComponent(name);

function make(render, payload, headers, $staropt$star, _) {
  var lazy_ = $staropt$star ? $staropt$star[0] : false;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */(function (self) {
              Curry._1(self[/* send */4], /* Fetch */0);
              return self[/* state */2];
            }),
          /* didMount */(function (self) {
              if (lazy_ === false) {
                Curry._1(self[/* send */4], /* Fetch */0);
              }
              return /* NoUpdate */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._1(render, self[/* state */2]);
            }),
          /* initialState */(function () {
              return /* record */[
                      /* data */defaultValue,
                      /* reason : None */0,
                      /* status : Idle */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* data */state[/* data */0],
                              /* reason */state[/* reason */1],
                              /* status : Idle */0
                            ]]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(3, [
                            /* record */[
                              /* data */state[/* data */0],
                              /* reason */state[/* reason */1],
                              /* status : Fetching */1
                            ],
                            (function (self) {
                                fetch$1(payload, headers, /* () */0).then((function (prim) {
                                            return prim.json();
                                          })).then((function (json) {
                                          Curry._1(self[/* send */4], /* ParseData */[/* Success */Block.__(0, [decodeState(json)])]);
                                          return Promise.resolve(null);
                                        })).catch((function (err) {
                                        console.log("Error: ", err);
                                        Curry._1(self[/* send */4], /* ParseData */[/* Failed */Block.__(1, ["Fetch Error"])]);
                                        return Promise.resolve(null);
                                      }));
                                return /* () */0;
                              })
                          ]);
                }
              } else {
                var fetchedData = action[0];
                if (typeof fetchedData === "number") {
                  return /* NoUpdate */0;
                } else if (fetchedData.tag) {
                  return /* Update */Block.__(0, [/* record */[
                              /* data */state[/* data */0],
                              /* reason : Some */[fetchedData[0]],
                              /* status : Failed */2
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* data */fetchedData[0],
                              /* reason : None */0,
                              /* status : Idle */0
                            ]]);
                }
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var RLimit = /* module */[
  /* url */url$1,
  /* fetch */fetch$1,
  /* component */component,
  /* make */make
];

exports.CreateFetcherFactory = CreateFetcherFactory;
exports.CreateFetcher = CreateFetcher;
exports.RLimitConfig = RLimitConfig;
exports.RLimit = RLimit;
/* component Not a pure module */
