// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.bs.js");
var About = require("./About.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var WithHeader = require("./WithHeader.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("RootComponent");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              return ReasonReact.element(/* None */0, /* None */0, WithHeader.make(/* array */[match ? ReasonReact.element(/* None */0, /* None */0, About.make(/* array */[])) : ReasonReact.element(/* None */0, /* None */0, Home.make(/* array */[]))]));
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              var route = action[0];
              console.log("update route ", route);
              return /* Update */Block.__(0, [/* record */[/* route */route]]);
            }),
          /* subscriptions */(function (self) {
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                          var match = url[/* path */0];
                                          var tmp;
                                          if (match) {
                                            switch (match[0]) {
                                              case "about" : 
                                                  tmp = match[1] ? /* Home */0 : /* About */1;
                                                  break;
                                              case "" : 
                                              case "index" : 
                                                  tmp = /* Home */0;
                                                  break;
                                              default:
                                                tmp = /* Home */0;
                                            }
                                          } else {
                                            tmp = /* Home */0;
                                          }
                                          return Curry._1(self[/* send */3], /* UpdateRoute */[tmp]);
                                        }));
                          }),
                        ReasonReact.Router[/* unwatchUrl */2]
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.component = component;
exports.make = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
