// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.bs.js");
var About = require("./About.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function handleRoutes(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "about" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* About */1;
          }
      case "" : 
      case "index" : 
          return /* Home */0;
      default:
        return /* Home */0;
    }
  } else {
    return /* Home */0;
  }
}

function handleRouteComponents(route) {
  if (route) {
    return ReasonReact.element(/* None */0, /* None */0, About.make(/* array */[]));
  } else {
    return ReasonReact.element(/* None */0, /* None */0, Home.make(/* array */[]));
  }
}

function toKey(route) {
  if (route) {
    return "2";
  } else {
    return "1";
  }
}

function toString(route) {
  if (route) {
    return "About";
  } else {
    return "Home";
  }
}

exports.handleRoutes = handleRoutes;
exports.handleRouteComponents = handleRouteComponents;
exports.toKey = toKey;
exports.toString = toString;
/* Home Not a pure module */
