// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Antd_Menu = require("bs-ant-design/src/Antd_Menu.js");
var Antd_Layout = require("bs-ant-design/src/Antd_Layout.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var menu = Css.style(/* :: */[
      /* `declaration */[
        -434952966,
        /* tuple */[
          "lineHeight",
          "64px !important"
        ]
      ],
      /* [] */0
    ]);

var Styles = /* module */[/* menu */menu];

var component = ReasonReact.statelessComponent("Header");

function make(children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Antd_Layout.make(/* None */0, /* None */0, /* None */0, /* array */[
                              ReasonReact.element(/* None */0, /* None */0, Antd_Layout.Header[/* make */0](/* None */0, /* Some */["header"], /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Antd_Menu.make(/* Some */[/* Dark */758939798], /* Some */[/* Horizontal */208994564], /* None */0, /* None */0, /* Some */[/* array */["2"]], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[menu], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                                                  ReasonReact.element(/* Some */["1"], /* None */0, Antd_Menu.Item[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["nav 1"])),
                                                  ReasonReact.element(/* Some */["2"], /* None */0, Antd_Menu.Item[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["nav 2"])),
                                                  ReasonReact.element(/* Some */["3"], /* None */0, Antd_Menu.Item[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["nav 3"]))
                                                ]))])),
                              ReasonReact.element(/* None */0, /* None */0, Antd_Layout.Content[/* make */0](/* None */0, /* None */0, /* None */0, children))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* menu Not a pure module */
